#!/bin/bash

set -e

. $(dirname $0)/base

WORKDIR "/work/out/${QEMU_SRC_BASENAME}"
RUN make -j$(nproc) install
mkdir -p /work/dst/${QEMU_ARTIFACT_BASENAME}/etc/qemu
echo 'allow all' >/work/dst/${QEMU_ARTIFACT_BASENAME}/etc/qemu/bridge.conf
